### ISSUE TITLE
Subir los ficheros fuente del sitio web

### ISSUE THREAD

**Issue by JaimeObregon** [aleph8/aleph8.github.io#1]
👋  Querido amigo Alejandro:

Te prometí una _pull request_ y a eso venía… 😜 Pero no he encontrado en este repositorio la estructura de ficheros original a partir de la cual generas este sitio web. Todo lo que aquí hallo parece generado por un generador de sitios estáticos. ¿Es así o estoy equivocado?

Es por eso que te cambio la _pull request_ por este _issue_ y te animo a cargar al repositorio los contenidos originales también. 🙂

**Comment by JaimeObregon** [comment]
¡Genial, Alejandro! Me alegra charlar contigo. Te hago dos sugerencias; no por pretender robarte tiempo sino por si te resultaran útiles:

1. ¿No crees que quizá sería mejor publicar en la rama `main` los ficheros fuente del sitio web y no publicar en ningún lado los ficheros generados? Estos últimos, a fin de cuentas, se sobrescriben con cada despliegue, razón por la cual no tiene mucho sentido tenerlos bajo control de versiones. Por ejemplo: no se puede hacer un _pull request_ sobre ellos, ni son código evolucionable.

    En mis proyectos suelo publicar los ficheros fuente únicamente. Y los ficheros generados —los que se despliegan— no los tengo bajo control de versiones porque son un subproducto de los ficheros fuente. Los genero en el _runner_ que corre el trabajo de despliegue (GitHub Actions) y se copian al servidor después, pero no los tengo en ningún repositorio.

2. ¿Crees que tendría sentido poner la información que me pasas en el `README.md` del proyecto? Para que esté accesible de un primer golpe de vista a quien acceda al repositorio.

¿Qué te parece? No quiero complicarte la vida, son solo dos ideas… _My two cents_ :)

**Comment by aleph8** [comment]
¡Tienes razón! Tiene más sentido subir los ficheros fuentes.

Sin embargo, en algún lado deben estar los generados ya que estoy usando [GitHub Pages](https://pages.github.com/) para alojar la página, no ningún servidor externo (es por eso también que la web es estática y no dinámica). Entonces realmente cuando hago _pull_ al repositorio lo que estoy haciendo es actualizar la página.

¡Estructura organizada y README con información relevante añadido!
